### ISSUE TITLE
documentation and or examples

### ISSUE THREAD

**Issue by dominictarr** [bpmn-io/tiny-svg#1]
This sounds like something I might want to use but I can't tell because there isn't any examples so I don't know, could you provide a few examples or document how to use this?

**Comment by nikku** [comment]
As you figured out yourself, there isn't really anything there yet. I plan to use this library to replace [snapsvg](http://snapsvg.io) in one of my projects. However I had no time to do so.

The thing that is still missing is intersection logic (extracted from snapsvg/raphael).
Except for that this library aims to provide a few minimal helpers on top of the SVG API and most of the stuff is already implemented. Feel free to browse the sources and see if you can use the stuff.

**Comment by dominictarr** [comment]
All I'm asking for is a short example, that say, outputs 3 circles and a line.

**Comment by nikku** [comment]
Have a look at the [test cases](https://github.com/Nikku/tiny-svg/blob/master/test/spec/) that offer you exactly that.
