### ISSUE TITLE
tiny-svg breaks static site generation on Node.js

### ISSUE THREAD

**Issue by fskuteken** [bpmn-io/tiny-svg#10]
__Describe the Bug__

I am developing a project with [Next.js](https://nextjs.org/) that uses the [bpmn-js](https://github.com/bpmn-io/bpmn-js) package.
Next.js generates static versions of each page. On build-time, just by importing some classes from `bpmn-js`, we encounter an issue as `tiny-svg` is trying to access the `document` variable that does not exist on `Node.js`:

```ts
import Viewer from 'bpmn-js/lib/Viewer'

// ReferenceError: document is not defined
```

I reviewed the `tiny-svg` source code and found the following code:

https://github.com/bpmn-io/tiny-svg/blob/master/lib/geometry.js#L8
```js
// fake node used to instantiate svg geometry elements
var node = create('svg');

// internally calls document.createElementNS
```

I think the `node` variable above could be lazily created, fixing the issue.

__Steps to Reproduce__

1. Import some class from `bpmn-js`, such as `bpmn-js/lib/Viewer` in a Next.js project
2. Run `npm run build`

__Expected Behavior__

I expect that just importing a class from `bpmn-js/lib/Viewer` does not break an application that is generating static pages in Node.js

__Environment__

- Host (Browser/Node version), if applicable: N/A
- OS: N/A
- Library version: 2.2.3

**Comment by fskuteken** [comment]
My current workaround on Next.js is adding a mock for `document.createElementNS` in `next.config.js` on build time:

```js
// next.config.js
const { PHASE_PRODUCTION_BUILD } = require('next/constants')

if (process.env.NEXT_PHASE === PHASE_PRODUCTION_BUILD) {
  // eslint-disable-next-line no-unused-vars
  const document = { createElementNS: () => {} }
}
```

**Comment by nikku** [comment]
I guess the best path forward is to [mock document](https://www.npmjs.com/package/mock-browser). We're not set-up to work in Node (non-browser environments).
