### ISSUE TITLE
`innerSVG` does not escape < and > in attributes

### ISSUE THREAD

**Issue by barmac** [bpmn-io/tiny-svg#16]
### Describe the Bug

The `innerSVG(svg)` helper does not escape the attributes which leads to broken SVG.

### Steps to Reproduce

Cf. the test case in https://github.com/bpmn-io/tiny-svg/commit/83cd6a2ddc7b8b37f7fba30891dde394df0c308d

### Expected Behavior

The characters should be transformed into `&gt;` and `&lt;`.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

---

Related to https://github.com/camunda/camunda-modeler/issues/4127

**Comment by nikku** [comment]
Bug [here](https://github.com/bpmn-io/tiny-svg/blob/main/lib/util/serialize.js#L6)
