### ISSUE TITLE
Missing parts in select method type definitions

### ISSUE THREAD

**Issue by ceisele-r** [bpmn-io/tiny-svg#6]
Hi,

We are using diagram-js which pulls in tiny-svg as dependency. Unfortunately when building with tsc, it complains the following error:
`node_modules/tiny-svg/dist/index.d.ts:155:17 - error TS7010: 'select', which lacks return-type annotation, implicitly has an 'any' return type.`

When lookin at the code, it seems there is some code missing by mistake for the `select` method type definitions:
https://github.com/bpmn-io/tiny-svg/blob/f55966ef746a6d665b296556d9388279e3085879/lib/index.d.ts#L155

It seems that the second parameter (`selector`) as well as the return type are missing. Am I correct or am I missing something?

**Comment by nikku** [comment]
We are happy to take contributions that improve the existing type definitions. 

I'm not into TS so I cannot help.

**Comment by barmac** [comment]
It seems that the type definitions are incorrect in multiple places. The same applies to https://github.com/bpmn-io/tiny-svg/blob/f55966ef746a6d665b296556d9388279e3085879/lib/index.d.ts#L157-L163

Feel free to fill a pull request with fixes.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/tiny-svg/pull/7.
